### ISSUE TITLE
"undefined: gologger.Errorf/gologger/Warningf" errors for tools on Windows

### ISSUE THREAD

**Issue by awasthi7** [projectdiscovery/gologger#8]
I get these errors on Windows system when trying to install any project-discovery tool from source.

**Comment by bauthard** [comment]
Hi @awasthi7, This is not an issue, just make sure you are **NOT** using `-u` flag along with cmd to install projects, if you doing, just remove `-u` flag and you will be able to install the projects.

**Comment by awasthi7** [comment]
I have been simply using the "go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder".

**Comment by bauthard** [comment]
@awasthi7 `GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder` is the right command.

**Comment by awasthi7** [comment]
tried that but I get  "'GO111MODULE' is not recognized as an internal or external command,
operable program or batch file".

**Comment by awasthi7** [comment]
go version go1.15.2 windows/amd64

**Comment by bauthard** [comment]
in that case, you need to search how to enable or use `GO111MODULE` on windows or just download the compiled binary of subfinder for windows OS from the release section of the project.

**Comment by fnbf** [comment]
Make sure your project is pulling in ➡️  `github.com/projectdiscovery/gologger v1.0.1` in go.mod.  You are running a newer version of gologger which deprecated WarningF, VerboseF, etc... 

https://github.com/projectdiscovery/gologger/commit/45299ff7c41b24e1a148b42093912762df7cb266#diff-77b54c0915ac7ed900c4f0735b6349bf8843dc3d3f82cb9851e0ff9a666a181eL156

This semver should have been a major version bump since it has breaking changes.
